### PR TITLE
Important JS topics

### PR DESCRIPTION
**Pull request by yashi12**
I have added important topics to be learnt in JS (advanced topics) usually which students do not consider. Issue( #1)

### CODE REVIEW

**Comment by vyasriday** [comment]
This is just a list of topics and it's pdf. I am sorry but I can't merge it.

**Comment by yashi12** [comment]
> This is just a list of topics and it's pdf. I am sorry but I can't merge it.

I converted list to PDF so that it becomes easy for user to understand.
Can u plz suggest what else do u want in it so that I can add those things to it?

**Comment by vyasriday** [comment]
This repo contains some info about the topic mentioned. Yours is just a list of topics which can be useful. You can list those topics here but it would be great if you could write something about the topic you know.

**Comment by yashi12** [comment]
> This repo contains some info about the topic mentioned. Yours is just a list of topics which can be useful. You can list those topics here but it would be great if you could write something about the topic you 

Sure I will write about some of the topics.

**Comment by yashi12** [comment]
> This repo contains some info about the topic mentioned. Yours is just a list of topics which can be useful. You can list those topics here but it would be great if you could write something about the topic you know.

Plz have a look at the PR, I have made the changes to it, and plz merge it:
Changed from Pdf to markdown 
Added content about the topics -->(Keywords,Promises,Async-Await, Requests)
Added Code snippets to describe them

**Comment by yashi12** [comment]
@vyasriday plz view my PR

**Review by vyasriday — APPROVED** [review]

**Pull request merged**
